/**
 * Downloads the Fredoka woff2 subsets (SIL OFL 1.1) from Google Fonts into `public/fonts/` and
 * generates `src/fonts.css`. Run once: `docker compose run --rm fonts`. The result is committed,
 * so neither the build nor CI ever touches the network.
 *
 * Everything is fetched and checked in memory first and written through a temporary file, so a
 * failure (no internet, a truncated file, an unexpected response) leaves the repository untouched.
 */
import { mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(root, 'public', 'fonts');
const CSS_FILE = join(root, 'src', 'fonts.css');

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&display=block';
const OFL_URL = 'https://raw.githubusercontent.com/google/fonts/main/ofl/fredoka/OFL.txt';
// Google serves woff2 only to browsers; with Node's own user agent the answer is a fat TTF.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
// Czech needs both: ě š č ř ž ů ď ť ň live in latin-ext, the rest of the alphabet in latin.
const SUBSETS = ['latin', 'latin-ext'];
const MIN_BYTES = 2 * 1024; // latin-ext is a ~4.6 kB subset; this only has to catch an error page
const MAX_BYTES = 500 * 1024;

class FetchFontsError extends Error {}

function fail(message) {
  throw new FetchFontsError(message);
}

async function download(url, expect) {
  let response;
  try {
    response = await fetch(url, { headers: { 'User-Agent': UA } });
  } catch (error) {
    fail(`${url} is unreachable (${error instanceof Error ? error.message : String(error)})`);
  }
  if (!response.ok) fail(`${url} answered HTTP ${response.status}`);
  return expect === 'text' ? response.text() : new Uint8Array(await response.arrayBuffer());
}

/** Google's stylesheet is one `/* subset *\/` comment plus one @font-face block per subset. */
function parseSubsets(css) {
  const blocks = new Map();
  const pattern = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  for (const [, name, body] of css.matchAll(pattern)) {
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1]?.replace(/['"]/g, '');
    const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    const stretch = /font-stretch:\s*([^;]+);/.exec(body)?.[1]?.trim();
    if (url && range) blocks.set(name, { url, range, stretch });
  }
  return blocks;
}

function checkWoff2(name, bytes) {
  const magic = new TextDecoder().decode(bytes.subarray(0, 4));
  if (magic !== 'wOF2') fail(`${name}: not a woff2 file (magic "${magic}")`);
  if (bytes.byteLength < MIN_BYTES || bytes.byteLength > MAX_BYTES) {
    fail(`${name}: suspicious size ${bytes.byteLength} B (expected ${MIN_BYTES}–${MAX_BYTES} B)`);
  }
}

function fontFace(subset, { range, stretch }) {
  return [
    '@font-face {',
    '  font-family: Fredoka;',
    '  font-style: normal;',
    '  font-weight: 300 700;',
    ...(stretch ? [`  font-stretch: ${stretch};`] : []),
    // The files are local and load in milliseconds; `swap` would flash a fallback font exactly
    // on the letters the child is learning.
    '  font-display: block;',
    `  src: url('/fonts/Fredoka-${subset}.woff2') format('woff2');`,
    `  unicode-range: ${range};`,
    '}',
  ].join('\n');
}

/** Write through a temporary file so an interrupted run cannot leave half a font behind. */
function writeAtomic(path, contents) {
  const temp = `${path}.tmp`;
  writeFileSync(temp, contents);
  renameSync(temp, path);
}

async function main() {
  const css = await download(CSS_URL, 'text');
  const blocks = parseSubsets(css);

  const files = [];
  for (const subset of SUBSETS) {
    const block = blocks.get(subset);
    if (!block)
      fail(`the stylesheet has no "${subset}" subset (got: ${[...blocks.keys()].join(', ')})`);
    if (!block.url.startsWith('https://fonts.gstatic.com/'))
      fail(`${subset}: unexpected font host ${block.url}`);
    const bytes = await download(block.url, 'bytes');
    checkWoff2(subset, bytes);
    files.push({ name: `Fredoka-${subset}.woff2`, bytes, block, subset });
  }

  const ofl = await download(OFL_URL, 'text');
  if (!ofl.includes('SIL OPEN FONT LICENSE'))
    fail('OFL.txt does not look like the SIL Open Font License');

  const stylesheet = [
    '/* Generated by scripts/fetch-fonts.mjs – do not edit by hand.',
    ' * Fredoka, SIL OFL 1.1 – the license text is in public/fonts/OFL.txt. */',
    ...files.map(({ subset, block }) => fontFace(subset, block)),
    '',
  ].join('\n');

  mkdirSync(FONT_DIR, { recursive: true });
  for (const { name, bytes } of files) writeAtomic(join(FONT_DIR, name), bytes);
  writeAtomic(join(FONT_DIR, 'OFL.txt'), ofl);
  writeAtomic(CSS_FILE, stylesheet);

  for (const { name, bytes } of files) {
    console.log(`public/fonts/${name}  ${(bytes.byteLength / 1024).toFixed(1)} kB`);
  }
  console.log(`public/fonts/OFL.txt  ${(ofl.length / 1024).toFixed(1)} kB`);
  console.log('src/fonts.css written');
}

try {
  await main();
} catch (error) {
  console.error(`fetch-fonts: ${error instanceof FetchFontsError ? error.message : error}`);
  process.exit(1);
}
