import './fonts.css'; // generated by scripts/fetch-fonts.mjs – self-hosted Fredoka
import './style.css';
import { createAudioEngine } from './audio/context';
import { createSfxPlayer } from './audio/sfx';
import { createVoicePlayer } from './audio/voice';
import { type Letter } from './data/curriculum';
import { letterOrder } from './game/curriculum';
import { generateOrder, type Order } from './game/orders';
import { createRng, systemRng } from './game/rng';
import { createSession } from './game/session';
import { orderPreload } from './game/speech';
import { mergeSave } from './game/merge';
import {
  parseSave,
  readSave,
  resetSave,
  writeSave,
  withSettings,
  type SaveData,
  type StorageLike,
} from './game/save';
import { EMPTY_SETTINGS, normalizeSettings, type Settings } from './game/settings';
import { SAVE_BACKUP_KEY, SAVE_KEY } from './game/version';
import { kitchenScene } from './scenes/kitchen';
import { titleScene } from './scenes/title';
import { createOrientationGuard } from './stage/orientation';
import { createSceneManager } from './stage/scenes';
import { createStage } from './stage/stage';

/** Reading `localStorage` itself can throw when the browser blocks site data. */
function browserStorage(): StorageLike {
  try {
    const storage = window.localStorage;
    storage.getItem(SAVE_KEY);
    return storage;
  } catch {
    const memory = new Map<string, string>();
    return {
      getItem: (key) => memory.get(key) ?? null,
      setItem: (key, value) => void memory.set(key, value),
      removeItem: (key) => void memory.delete(key),
    };
  }
}

const app = document.querySelector<HTMLElement>('#app');
if (app) {
  const storage = browserStorage();
  // One session for the whole run: it holds the order the kitchen is filling and is the only
  // thing that writes the save – when an order is completed (rule 4).
  const session = createSession(storage);

  const stage = createStage(app);
  const audio = createAudioEngine();
  // The narrator outlives the scenes: it is created here, before the first tap, so the clips of
  // this order are already on the device by the time the kitchen opens. Fetching needs no audio
  // context – only the decoding waits for the unlock (rule 6).
  const voice = createVoicePlayer({ engine: audio });
  voice.preload(orderPreload(session.order));
  // The whole effect set is 172 kB: small enough to pull down at once, and the first tap must be
  // answered instantly. Decoding waits for the unlock; the kitchen asks again when it mounts.
  const sfx = createSfxPlayer({ engine: audio });
  sfx.preload();
  const scenes = createSceneManager(
    { stage, audio, voice, sfx, session },
    { title: titleScene, kitchen: kitchenScene },
  );
  const orientation = createOrientationGuard(app, { voice });
  scenes.go('title');

  if (import.meta.env.DEV) {
    // Handles for the manual checks in docs/steps/STEP-02-*.md and STEP-03-*.md; stripped from
    // the build, so real names never reach the deployed game (settings UI comes in STEP-19).
    Object.assign(window, {
      __stage: stage,
      __audio: audio,
      __voice: {
        say: (lines: string | readonly string[]): void => voice.say(lines),
        stop: (): void => voice.stop(),
        preload: (lines: readonly string[]): void => voice.preload(lines),
        /** For the manual checks: "did that tap actually say anything?" */
        get speaking(): boolean {
          return voice.speaking;
        },
      },
      __sfx: {
        play: (id: string, rate?: number): void => sfx.play(id, { rate }),
        preload: (): void => sfx.preload(),
        /** For the manual checks: "is the whole set decoded?" */
        get ready(): boolean {
          return sfx.ready;
        },
      },
      __scenes: scenes,
      __orientation: orientation,
      __session: session,
      __save: {
        read: (): SaveData => readSave(storage),
        write: (data: SaveData): void => writeSave(storage, data),
        reset: (): SaveData => resetSave(storage),
        raw: (): string | null => storage.getItem(SAVE_KEY),
        backup: (): string | null => storage.getItem(SAVE_BACKUP_KEY),
        /**
         * Merges a record from another device into the saved one and writes the result (STEP-13).
         * Text or object: an object is serialised first, so both go through `parseSave()` and
         * therefore through the migration. Unreadable input → null and nothing is written. The
         * running session keeps its own copy, so reload to see the merged record in the kitchen.
         */
        merge: (incoming: unknown): SaveData | null => {
          const raw = typeof incoming === 'string' ? incoming : JSON.stringify(incoming ?? null);
          const parsed = parseSave(raw);
          if (!parsed) return null;
          const merged = mergeSave(readSave(storage), parsed);
          writeSave(storage, merged);
          return merged;
        },
      },
      __settings: {
        get: (): Settings => readSave(storage).settings,
        set: (input: unknown): { settings: Settings; order: Letter[] } => {
          const settings = normalizeSettings(input);
          writeSave(storage, withSettings(readSave(storage), settings));
          return { settings, order: letterOrder(settings) };
        },
        clear: (): Settings => {
          writeSave(storage, withSettings(readSave(storage), EMPTY_SETTINGS));
          return EMPTY_SETTINGS;
        },
      },
      __game: {
        /** Stateless: reads the saved game every time; with a `seed` the result is repeatable. */
        order: (index = 1, seed?: number): Order => {
          const save = readSave(storage);
          return generateOrder({
            settings: save.settings,
            tracks: save.tracks,
            index,
            rng: seed === undefined ? systemRng : createRng(seed),
          });
        },
      },
    });
  }
}
