/**
 * The manifest of every Czech voice line of M1 (docs/navrh-hry.md ch. 5.5, 5.6, 8) plus the helpers
 * that turn game data into a line id. One id = one file `public/audio/voice/<id>.mp3`, generated by
 * `scripts/generate-voice.mjs`. Sentences are always whole: Czech declines (tři jahody × pět jahod)
 * and a sentence is never stitched together from fragments at runtime (CLAUDE.md rule 7).
 *
 * The texts are Czech because they are game content; everything around them is English.
 *
 * CAREFUL: this file is also read by plain Node (the generator, type stripping), and Node resolves
 * no extensionless specifiers. Value imports must therefore carry the `.ts` extension and may only
 * come from `./curriculum.ts`; anything else has to be an `import type`, which is erased on load.
 */
import {
  BASE_LETTERS,
  FRUITS,
  isLetter,
  LETTER_WORDS,
  ROLE_WORDS,
  type FruitKind,
  type Letter,
} from './curriculum.ts';

/** Who says the line. STEP-10 adds 'animal' for the customers. */
export type VoiceRole = 'narrator';

export interface Line {
  /** Stable id and file name at once: `^[a-z0-9]+([.-][a-z0-9]+)*$`. */
  readonly id: string;
  /** One whole Czech sentence. */
  readonly text: string;
  /** Defaults to 'narrator'. */
  readonly voice?: VoiceRole;
}

/** Which set of praises the child hears; the setting arrives in STEP-19, until then 'neutral'. */
export type PraiseGender = 'neutral' | 'female' | 'male';

/** The numbers of M1 – the first ten, never a zero (návrh 5.2). */
const DIGITS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const;

type Digit = (typeof DIGITS)[number];

/**
 * Letter names as they are read aloud. A bare "K" is a riddle for the TTS (kilo? ká?), the Czech
 * name is not; the letter itself stays in the id and on the cookie.
 */
const SPELLED: Readonly<Record<Letter, string>> = {
  A: 'á',
  B: 'bé',
  C: 'cé',
  D: 'dé',
  E: 'é',
  F: 'ef',
  G: 'gé',
  H: 'há',
  I: 'í',
  J: 'jé',
  K: 'ká',
  L: 'el',
  M: 'em',
  N: 'en',
  O: 'ó',
  P: 'pé',
  R: 'er',
  S: 'es',
  T: 'té',
  U: 'ú',
  V: 'vé',
  Z: 'zet',
};

/** Accusative numerals – all three fruits are feminine, so one row is enough. */
const NUMERALS: Readonly<Record<Digit, string>> = {
  1: 'jednu',
  2: 'dvě',
  3: 'tři',
  4: 'čtyři',
  5: 'pět',
  6: 'šest',
  7: 'sedm',
  8: 'osm',
  9: 'devět',
  10: 'deset',
};

/** The plain counting row (návrh 5.6) – also what goes after "s číslem". */
const CARDINALS: Readonly<Record<Digit, string>> = {
  1: 'jedna',
  2: 'dva',
  3: 'tři',
  4: 'čtyři',
  5: 'pět',
  6: 'šest',
  7: 'sedm',
  8: 'osm',
  9: 'devět',
  10: 'deset',
};

/** The digit as a thing the child looks for: "To je pětka." */
const DIGIT_NAMES: Readonly<Record<Digit, string>> = {
  1: 'jednička',
  2: 'dvojka',
  3: 'trojka',
  4: 'čtyřka',
  5: 'pětka',
  6: 'šestka',
  7: 'sedmička',
  8: 'osmička',
  9: 'devítka',
  10: 'desítka',
};

/** The same in the accusative: "Hledáme trojku." */
const DIGIT_NAMES_ACC: Readonly<Record<Digit, string>> = {
  1: 'jedničku',
  2: 'dvojku',
  3: 'trojku',
  4: 'čtyřku',
  5: 'pětku',
  6: 'šestku',
  7: 'sedmičku',
  8: 'osmičku',
  9: 'devítku',
  10: 'desítku',
};

/** One row per fruit instead of 30 hand-written sentences – 30 chances for a declension typo. */
const FRUIT_FORMS: Readonly<
  Record<FruitKind, { readonly one: string; readonly few: string; readonly many: string }>
> = {
  strawberry: { one: 'jednu jahodu', few: 'jahody', many: 'jahod' },
  blueberry: { one: 'jednu borůvku', few: 'borůvky', many: 'borůvek' },
  cherry: { one: 'jednu třešeň', few: 'třešně', many: 'třešní' },
};

/** Praise, three sets (návrh kap. 8). The gender is the child's, see PraiseGender. */
const PRAISE: Readonly<Record<PraiseGender, readonly string[]>> = {
  neutral: [
    'Výborně!',
    'Přesně tak!',
    'To je ono!',
    'Paráda!',
    'Skvělá práce!',
    'Jde ti to!',
    'Máme to!',
    'Ano, správně!',
    'Bezvadné!',
    'Tak je to správně!',
  ],
  female: [
    'Šikovná!',
    'Jsi moc šikovná!',
    'Zvládla jsi to!',
    'Ty jsi ale chytrá!',
    'Jsi malá kuchařka!',
    'Udělala jsi to správně!',
  ],
  male: [
    'Šikovný!',
    'Jsi moc šikovný!',
    'Zvládl jsi to!',
    'Ty jsi ale chytrý!',
    'Jsi malý kuchař!',
    'Udělal jsi to správně!',
  ],
};

/** The order is done (návrh kap. 4): the finale of the cake, before the star flies. */
const FINISH: readonly string[] = ['Hotovo!', 'A je to!', 'Dortík je hotový!'];

/** The reward lands in the counter (návrh kap. 7). */
const STAR: readonly string[] = ['Máš hvězdičku!', 'Hvězdička je tvoje!'];

/**
 * The counter is empty and the bell is waiting (návrh kap. 4). Said only after 15 s of silence –
 * the child is meant to find the bell, not be told about it the moment it appears.
 */
const BELL: readonly string[] = ['Zazvoň na zvoneček!', 'Klepni na zvoneček!'];

/**
 * The tenth order of a sitting is done and the shutter is coming down (návrh kap. 4). Said over the
 * rattle, once – the picture (a shutter and a kitchen timer) is what carries the message.
 */
const CLOSING: readonly string[] = [
  'Kuchyně dneska zavírá, dobrou noc!',
  'Kuchyně zavírá. Ahoj a přijď zas!',
];

/** A tap on the shutter, and the answer to a kitchen that opens already closed. */
const CLOSED: readonly string[] = [
  'Kuchyně má zavřeno. Přijď zase za chvilku!',
  'Teď je zavřeno. Až doběhnou hodiny, otevřeme!',
];

/** The shutter goes back up – the timer ran out, or a grown-up typed the code. */
export const OPEN_LINE = 'open.1';
const OPEN_TEXT = 'Kuchyně je zase otevřená!';

/** The portrait overlay of `stage/orientation.ts` – a picture plus this one sentence (rule 1). */
export const TURN_LINE = 'guard.turn';
const TURN_TEXT = 'Otoč mě!';

/**
 * Five sample sentences for the casting (návrh kap. 8): they are never generated together with
 * LINES, only under `--casting`, and they cover an order, a praise, a correction, the stop of
 * counting and the end of a session.
 */
export const CASTING_LINES: readonly Line[] = [
  { id: 'casting.1', text: 'Prosím tři jahody a perníček s písmenkem ká!' },
  { id: 'casting.2', text: 'Výborně, přesně tak!' },
  { id: 'casting.3', text: 'To je bé. Hledáme ká.' },
  { id: 'casting.4', text: 'Už máme tři jahody, to stačí!' },
  { id: 'casting.5', text: 'Kuchyně dneska zavírá, dobrou noc!' },
];

/** "kočka" → "kocka". DIACRITICS in curriculum.ts maps single letters, not whole words. */
function slug(word: string): string {
  return word
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/** "jednu jahodu" / "dvě jahody" / "pět jahod". */
function countedFruit(amount: Digit, fruit: FruitKind): string {
  const forms = FRUIT_FORMS[fruit];
  if (amount === 1) return forms.one;
  return `${NUMERALS[amount]} ${amount <= 4 ? forms.few : forms.many}`;
}

/**
 * Letter or digit? `target` is a track element exactly as `ChoiceState.target` and `TrackState`
 * hold it: an upper-case letter ('K') or a digit as a string ('3', '10'). Whatever is not one of
 * the 22 base letters goes down the digit branch – and if it is not a digit of M1 either, the id
 * simply has no clip and the game stays silent (rule 2: a mistake never blocks the game).
 */
function targetKind(target: string): 'letter' | 'digit' {
  return isLetter(target) ? 'letter' : 'digit';
}

export function orderCountLine(amount: number, fruit: FruitKind): string {
  return `order.count.${amount}.${fruit}`;
}

export function orderDigitLine(value: number): string {
  return `order.digit.${value}`;
}

export function orderLetterLine(letter: Letter): string {
  return `order.letter.${letter.toLowerCase()}`;
}

/**
 * The same order, said as the SECOND thing the customer asks for: "Prosím tři jahody. A ještě
 * perníček s písmenkem ká." (STEP-12). A whole sentence again, never "Prosím …" with an "a ještě"
 * glued in front of it – rule 7. Which form is used is decided by the position in what is being
 * SAID, not by the position in the order: an item left on its own goes back to "Prosím …", so a
 * bare "A ještě…" is never heard (see game/speech.ts).
 */
export function orderNextCountLine(amount: number, fruit: FruitKind): string {
  return `order.next.count.${amount}.${fruit}`;
}

export function orderNextDigitLine(value: number): string {
  return `order.next.digit.${value}`;
}

export function orderNextLetterLine(letter: Letter): string {
  return `order.next.letter.${letter.toLowerCase()}`;
}

/** The word comes from `letterWord()` – "B jako brácha" when there is a brother, else "balón". */
export function letterWordLine(letter: Letter, word: string): string {
  return `letter.word.${letter.toLowerCase()}.${slug(word)}`;
}

export function countAloudLine(step: number): string {
  return `count.${step}`;
}

export function countEnoughLine(amount: number, fruit: FruitKind): string {
  return `count.enough.${amount}.${fruit}`;
}

export function wrongLine(target: string): string {
  return `wrong.${targetKind(target)}.${target.toLowerCase()}`;
}

export function seekLine(target: string): string {
  return `seek.${targetKind(target)}.${target.toLowerCase()}`;
}

export function hintLine(target: string): string {
  return `hint.${targetKind(target)}.${target.toLowerCase()}`;
}

export function praiseLines(gender: PraiseGender): readonly string[] {
  return PRAISE[gender].map((_, index) => `praise.${gender}.${index + 1}`);
}

export function finishLines(): readonly string[] {
  return FINISH.map((_, index) => `finish.${index + 1}`);
}

export function starLines(): readonly string[] {
  return STAR.map((_, index) => `star.${index + 1}`);
}

export function bellLines(): readonly string[] {
  return BELL.map((_, index) => `bell.${index + 1}`);
}

export function closingLines(): readonly string[] {
  return CLOSING.map((_, index) => `closing.${index + 1}`);
}

export function closedLines(): readonly string[] {
  return CLOSED.map((_, index) => `closed.${index + 1}`);
}

const lines: Line[] = [];
const ids = new Set<string>();

/**
 * Duplicates are skipped, not reported: the same letter+word pair legitimately arrives from both
 * LETTER_WORDS and ROLE_WORDS (M jako maminka). Everything else is unique by construction and the
 * test guards it.
 */
function add(id: string, text: string): void {
  if (ids.has(id)) return;
  ids.add(id);
  lines.push({ id, text });
}

for (const fruit of FRUITS) {
  for (const amount of DIGITS) {
    add(orderCountLine(amount, fruit), `Prosím ${countedFruit(amount, fruit)}.`);
    add(orderNextCountLine(amount, fruit), `A ještě ${countedFruit(amount, fruit)}.`);
    add(countEnoughLine(amount, fruit), `Už máme ${countedFruit(amount, fruit)}, to stačí!`);
  }
}

for (const digit of DIGITS) {
  const target = String(digit);
  add(orderDigitLine(digit), `Prosím svíčku s číslem ${CARDINALS[digit]}.`);
  add(orderNextDigitLine(digit), `A ještě svíčku s číslem ${CARDINALS[digit]}.`);
  add(countAloudLine(digit), `${capitalize(CARDINALS[digit])}.`);
  add(wrongLine(target), `To je ${DIGIT_NAMES[digit]}.`);
  add(seekLine(target), `Hledáme ${DIGIT_NAMES_ACC[digit]}.`);
  add(hintLine(target), `${capitalize(DIGIT_NAMES[digit])} je tady!`);
}

for (const letter of BASE_LETTERS) {
  const spelled = SPELLED[letter];
  add(orderLetterLine(letter), `Prosím perníček s písmenkem ${spelled}.`);
  add(orderNextLetterLine(letter), `A ještě perníček s písmenkem ${spelled}.`);
  add(wrongLine(letter), `To je ${spelled}.`);
  add(seekLine(letter), `Hledáme ${spelled}.`);
  add(hintLine(letter), `${capitalize(spelled)} je tady!`);
  add(
    letterWordLine(letter, LETTER_WORDS[letter]),
    `${capitalize(spelled)} jako ${LETTER_WORDS[letter]}.`,
  );
}

// Family words on top of the defaults: brácha, ségra, babička, děda (maminka and táta are already
// in LETTER_WORDS). Which of them the child hears is decided by the settings at runtime.
for (const entry of ROLE_WORDS) {
  add(
    letterWordLine(entry.letter, entry.word),
    `${capitalize(SPELLED[entry.letter])} jako ${entry.word}.`,
  );
}

for (const gender of ['neutral', 'female', 'male'] as const) {
  const texts = PRAISE[gender];
  for (const [index, text] of texts.entries()) add(`praise.${gender}.${index + 1}`, text);
}

for (const [index, text] of FINISH.entries()) add(`finish.${index + 1}`, text);
for (const [index, text] of STAR.entries()) add(`star.${index + 1}`, text);
for (const [index, text] of BELL.entries()) add(`bell.${index + 1}`, text);
for (const [index, text] of CLOSING.entries()) add(`closing.${index + 1}`, text);
for (const [index, text] of CLOSED.entries()) add(`closed.${index + 1}`, text);
add(OPEN_LINE, OPEN_TEXT);
add(TURN_LINE, TURN_TEXT);

export const LINES: readonly Line[] = lines;

/** Does the clip exist? Every helper returns an id even for input out of range, this decides. */
export function hasLine(id: string): boolean {
  return ids.has(id);
}
