/**
 * The manifest of every Czech voice line of M1 (docs/navrh-hry.md ch. 5.5, 5.6, 8) plus the helpers
 * that turn game data into a line id. One id = one file `public/audio/voice/<id>.mp3`, generated by
 * `scripts/generate-voice.mjs`. Sentences are always whole: Czech declines (tři jahody × pět jahod)
 * and a sentence is never stitched together from fragments at runtime (CLAUDE.md rule 7).
 *
 * The texts are Czech because they are game content; everything around them is English.
 *
 * CAREFUL: this file is also read by plain Node (the generator, type stripping), and Node resolves
 * no extensionless specifiers. Value imports must therefore carry the `.ts` extension and may only
 * come from `./curriculum.ts`, `./shop.ts` and `./products.ts` (all three are import-free
 * themselves); anything else has to be an `import type`, which is erased on load.
 */
import {
  BASE_LETTERS,
  FRUITS,
  isLetter,
  LETTER_WORDS,
  ROLE_WORDS,
  type FruitKind,
  type Letter,
} from './curriculum.ts';
import { PRODUCTS, productOf, type ProductId } from './products.ts';
import { SHOP_ITEMS, type ShopItemId } from './shop.ts';

/** Who says the line. STEP-10 adds 'animal' for the customers. */
export type VoiceRole = 'narrator';

export interface Line {
  /** Stable id and file name at once: `^[a-z0-9]+([.-][a-z0-9]+)*$`. */
  readonly id: string;
  /** One whole Czech sentence. */
  readonly text: string;
  /** Defaults to 'narrator'. */
  readonly voice?: VoiceRole;
}

/** Which set of praises the child hears; the setting arrives in STEP-22, until then 'neutral'. */
export type PraiseGender = 'neutral' | 'female' | 'male';

/** The numbers of M1 – the first ten, never a zero (návrh 5.2). */
const DIGITS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const;

type Digit = (typeof DIGITS)[number];

/**
 * Letter names as they are read aloud. A bare "K" is a riddle for the TTS (kilo? ká?), the Czech
 * name is not; the letter itself stays in the id and on the cookie.
 */
const SPELLED: Readonly<Record<Letter, string>> = {
  A: 'á',
  B: 'bé',
  C: 'cé',
  D: 'dé',
  E: 'é',
  F: 'ef',
  G: 'gé',
  H: 'há',
  I: 'í',
  J: 'jé',
  K: 'ká',
  L: 'el',
  M: 'em',
  N: 'en',
  O: 'ó',
  P: 'pé',
  R: 'er',
  S: 'es',
  T: 'té',
  U: 'ú',
  V: 'vé',
  Z: 'zet',
};

/**
 * A few letter names need a phonetic spelling for the TTS.  This applies only to the
 * “X jako …” teaching line: the other prompts retain the conventional Czech name.
 */
const SPELLED_IN_WORD_LINE: Readonly<Partial<Record<Letter, string>>> = {
  A: 'aa',
  E: 'ee',
  L: 'ell',
  N: 'enn',
  Z: 'zet,',
};

/**
 * Accusative numerals. One row is enough: whatever a product counts, it is fruit, and all four
 * fruits are feminine. (STEP-17 briefly counted scoops – masculine, "dva kopečky" – and needed
 * a second row; the ice cream now arrives finished and counts nothing, see návrh kap. 4.)
 */
const NUMERALS: Readonly<Record<Digit, string>> = {
  1: 'jednu',
  2: 'dvě',
  3: 'tři',
  4: 'čtyři',
  5: 'pět',
  6: 'šest',
  7: 'sedm',
  8: 'osm',
  9: 'devět',
  10: 'deset',
};

/** The plain counting row (návrh 5.6) – also what goes after "s číslem". */
const CARDINALS: Readonly<Record<Digit, string>> = {
  1: 'jedna',
  2: 'dva',
  3: 'tři',
  4: 'čtyři',
  5: 'pět',
  6: 'šest',
  7: 'sedm',
  8: 'osm',
  9: 'devět',
  10: 'deset',
};

/** The digit as a thing the child looks for: "To je pětka." */
const DIGIT_NAMES: Readonly<Record<Digit, string>> = {
  1: 'jednička',
  2: 'dvojka',
  3: 'trojka',
  4: 'čtyřka',
  5: 'pětka',
  6: 'šestka',
  7: 'sedmička',
  8: 'osmička',
  9: 'devítka',
  10: 'desítka',
};

/** The same in the accusative: "Hledáme trojku." */
const DIGIT_NAMES_ACC: Readonly<Record<Digit, string>> = {
  1: 'jedničku',
  2: 'dvojku',
  3: 'trojku',
  4: 'čtyřku',
  5: 'pětku',
  6: 'šestku',
  7: 'sedmičku',
  8: 'osmičku',
  9: 'devítku',
  10: 'desítku',
};

/** One row per fruit instead of 30 hand-written sentences – 30 chances for a declension typo. */
const FRUIT_FORMS: Readonly<
  Record<FruitKind, { readonly one: string; readonly few: string; readonly many: string }>
> = {
  strawberry: { one: 'jednu jahodu', few: 'jahody', many: 'jahod' },
  blueberry: { one: 'jednu borůvku', few: 'borůvky', many: 'borůvek' },
  cherry: { one: 'jednu třešeň', few: 'třešně', many: 'třešní' },
  raspberry: { one: 'jednu malinu', few: 'maliny', many: 'malin' },
};

/**
 * What carries the letter and the digit on each product, in the accusative – the noun of "Prosím …
 * s písmenkem ká." The picture is different for every product, and so is the word for it.
 */
const PRODUCT_TEXTS: Readonly<
  Record<ProductId, { readonly letter: string; readonly digit: string }>
> = {
  cake: { letter: 'perníček', digit: 'svíčku' },
  icecream: { letter: 'oplatku', digit: 'vlaječku' },
  pancakes: { letter: 'čokoládu', digit: 'cedulku' },
};

/** Praise, three sets (návrh kap. 8). The gender is the child's, see PraiseGender. */
const PRAISE: Readonly<Record<PraiseGender, readonly string[]>> = {
  neutral: [
    'Výborně!',
    'Přesně tak!',
    'To je ono!',
    'Paráda!',
    'Skvělá práce!',
    'Jde ti to!',
    'Máme to!',
    'Ano, správně!',
    'Bezvadné!',
    'Tak je to správně!',
  ],
  female: [
    'Šikovná!',
    'Jsi moc šikovná!',
    'Zvládla jsi to!',
    'Ty jsi ale chytrá!',
    'Jsi malá kuchařka!',
    'Udělala jsi to správně!',
  ],
  male: [
    'Šikovný!',
    'Jsi moc šikovný!',
    'Zvládl jsi to!',
    'Ty jsi ale chytrý!',
    'Jsi malý kuchař!',
    'Udělal jsi to správně!',
  ],
};

/**
 * The order is done (návrh kap. 4): said while the glaze runs over it, before the star flies. Two
 * of them fit anything the kitchen makes; the ones that NAME the thing belong to one product only,
 * because "Dortík je hotový!" over an ice cream is simply not true. The id is the position in this
 * list, so a new product appends and never renumbers what is already generated.
 */
const FINISH: readonly { readonly text: string; readonly product?: ProductId }[] = [
  { text: 'Hotovo!' },
  { text: 'A je to!' },
  { text: 'Dortík je hotový!', product: 'cake' },
  { text: 'Zmrzlinka je hotová!', product: 'icecream' },
  { text: 'Palačinky jsou hotové!', product: 'pancakes' },
];

/** The reward lands in the counter (návrh kap. 7). */
const STAR: readonly string[] = ['Máš hvězdičku!', 'Hvězdička je tvoje!'];

/**
 * The counter is empty and the bell is waiting (návrh kap. 4). Said only after 15 s of silence –
 * the child is meant to find the bell, not be told about it the moment it appears.
 */
const BELL: readonly string[] = ['Zazvoň na zvoneček!', 'Klepni na zvoneček!'];

/**
 * The tenth order of a sitting is done and the shutter is coming down (návrh kap. 4). Said over the
 * rattle, once – the picture (a shutter and a kitchen timer) is what carries the message.
 */
const CLOSING: readonly string[] = [
  'Kuchyně dneska zavírá, dobrou noc!',
  'Kuchyně zavírá. Ahoj a přijď zas!',
];

/** A tap on the shutter, and the answer to a kitchen that opens already closed. */
const CLOSED: readonly string[] = [
  'Kuchyně má zavřeno. Přijď zase za chvilku!',
  'Teď je zavřeno. Až doběhnou hodiny, otevřeme!',
];

/**
 * The two sentences of the shop, one per thing on the shelf (STEP-15): the question the narrator
 * asks when the child taps it, and the answer when it is paid for. The price is IN the question
 * ("za tři hvězdičky"), so a price cannot be changed without rewriting the sentence – the test in
 * lines.cs.test.ts holds the two together. The table is keyed by `ShopItemId`, so a new thing in
 * the catalogue does not compile until it has both sentences.
 */
const SHOP_TEXTS: Readonly<Record<ShopItemId, { readonly ask: string; readonly bought: string }>> =
  {
    'fruit.raspberry': {
      ask: 'Chceš koupit maliny za tři hvězdičky?',
      bought: 'Maliny jsou tvoje!',
    },
    'customer.frog': {
      ask: 'Chceš pozvat žabku za pět hvězdiček?',
      bought: 'Žabka přijde na návštěvu!',
    },
    'decor.cat': {
      ask: 'Chceš koupit kočičku za pět hvězdiček?',
      bought: 'Kočička je tvoje!',
    },
    'decor.radio': {
      ask: 'Chceš koupit rádio za pět hvězdiček?',
      bought: 'Rádio je tvoje!',
    },
    'product.icecream': {
      ask: 'Chceš koupit zmrzlinku za pět hvězdiček?',
      bought: 'Zmrzlinka je tvoje! Můžeš ji dělat.',
    },
    'product.pancakes': {
      ask: 'Chceš koupit palačinky za pět hvězdiček?',
      bought: 'Palačinky jsou tvoje! Můžeš je dělat.',
    },
  };

/**
 * "Chybí ti tři hvězdičky." – five whole sentences and not one built from a numeral plus a noun:
 * Czech declines (jedna hvězdička × dvě hvězdičky × pět hvězdiček) and rule 7 forbids stitching.
 * Five is enough because nothing in the catalogue costs more than five stars.
 */
const SHOP_SHORT: readonly string[] = [
  'Chybí ti jedna hvězdička.',
  'Chybí ti dvě hvězdičky.',
  'Chybí ti tři hvězdičky.',
  'Chybí ti čtyři hvězdičky.',
  'Chybí ti pět hvězdiček.',
];

/** The shop opens (STEP-16); said once, while the shelf slides in. */
const SHOP_HELLO: readonly string[] = ['Vítej v obchůdku!', 'Co si dneska koupíme?'];

/** The shutter goes back up – the timer ran out, or a grown-up typed the code. */
export const OPEN_LINE = 'open.1';
const OPEN_TEXT = 'Kuchyně je zase otevřená!';

/** The portrait overlay of `stage/orientation.ts` – a picture plus this one sentence (rule 1). */
export const TURN_LINE = 'guard.turn';
const TURN_TEXT = 'Otoč mě!';

/**
 * Five sample sentences for the casting (návrh kap. 8): they are never generated together with
 * LINES, only under `--casting`, and they cover an order, a praise, a correction, the stop of
 * counting and the end of a session.
 */
export const CASTING_LINES: readonly Line[] = [
  { id: 'casting.1', text: 'Prosím tři jahody a perníček s písmenkem ká!' },
  { id: 'casting.2', text: 'Výborně, přesně tak!' },
  { id: 'casting.3', text: 'To je bé. Hledáme ká.' },
  { id: 'casting.4', text: 'Už máme tři jahody, to stačí!' },
  { id: 'casting.5', text: 'Kuchyně dneska zavírá, dobrou noc!' },
];

/** "kočka" → "kocka". DIACRITICS in curriculum.ts maps single letters, not whole words. */
function slug(word: string): string {
  return word
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/** "jednu jahodu" / "dvě jahody" / "pět jahod". */
function countedFruit(amount: Digit, fruit: FruitKind): string {
  const forms = FRUIT_FORMS[fruit];
  if (amount === 1) return forms.one;
  return `${NUMERALS[amount]} ${amount <= 4 ? forms.few : forms.many}`;
}

/**
 * What is appended to the id of an ORDER sentence: nothing for the cake, `.icecream` for the ice
 * cream. The cake keeps bare ids forever – its clips are generated and committed, and renaming an
 * id would throw them away (see the step plan, decision 7).
 */
function suffix(product?: ProductId): string {
  const found = product === undefined ? null : productOf(product);
  return found?.lineSuffix ? `.${found.lineSuffix}` : '';
}

/**
 * Letter or digit? `target` is a track element exactly as `ChoiceState.target` and `TrackState`
 * hold it: an upper-case letter ('K') or a digit as a string ('3', '10'). Whatever is not one of
 * the 22 base letters goes down the digit branch – and if it is not a digit of M1 either, the id
 * simply has no clip and the game stays silent (rule 2: a mistake never blocks the game).
 */
function targetKind(target: string): 'letter' | 'digit' {
  return isLetter(target) ? 'letter' : 'digit';
}

/** Counting never depends on the product: whatever is being made, what is counted is fruit. */
export function orderCountLine(amount: number, fruit: FruitKind): string {
  return `order.count.${amount}.${fruit}`;
}

export function orderDigitLine(value: number, product?: ProductId): string {
  return `order.digit.${value}${suffix(product)}`;
}

export function orderLetterLine(letter: Letter, product?: ProductId): string {
  return `order.letter.${letter.toLowerCase()}${suffix(product)}`;
}

/**
 * The same order, said as the SECOND thing the customer asks for: "Prosím tři jahody. A ještě
 * perníček s písmenkem ká." (STEP-12). A whole sentence again, never "Prosím …" with an "a ještě"
 * glued in front of it – rule 7. Which form is used is decided by the position in what is being
 * SAID, not by the position in the order: an item left on its own goes back to "Prosím …", so a
 * bare "A ještě…" is never heard (see game/speech.ts).
 */
export function orderNextCountLine(amount: number, fruit: FruitKind): string {
  return `order.next.count.${amount}.${fruit}`;
}

export function orderNextDigitLine(value: number, product?: ProductId): string {
  return `order.next.digit.${value}${suffix(product)}`;
}

export function orderNextLetterLine(letter: Letter, product?: ProductId): string {
  return `order.next.letter.${letter.toLowerCase()}${suffix(product)}`;
}

/** The word comes from `letterWord()` – "B jako brácha" when there is a brother, else "balón". */
export function letterWordLine(letter: Letter, word: string): string {
  return `letter.word.${letter.toLowerCase()}.${slug(word)}`;
}

export function countAloudLine(step: number): string {
  return `count.${step}`;
}

export function countEnoughLine(amount: number, fruit: FruitKind): string {
  return `count.enough.${amount}.${fruit}`;
}

export function wrongLine(target: string): string {
  return `wrong.${targetKind(target)}.${target.toLowerCase()}`;
}

export function seekLine(target: string): string {
  return `seek.${targetKind(target)}.${target.toLowerCase()}`;
}

export function hintLine(target: string): string {
  return `hint.${targetKind(target)}.${target.toLowerCase()}`;
}

export function praiseLines(gender: PraiseGender): readonly string[] {
  return PRAISE[gender].map((_, index) => `praise.${gender}.${index + 1}`);
}

/**
 * "Hotovo!" – the two that fit anything, plus the one that names this very product. Without a
 * product only the neutral ones come back, so nothing can be called a dortík by accident.
 */
export function finishLines(product?: ProductId): readonly string[] {
  return FINISH.map((entry, index) => ({ entry, id: `finish.${index + 1}` }))
    .filter(({ entry }) => entry.product === undefined || entry.product === product)
    .map(({ id }) => id);
}

export function starLines(): readonly string[] {
  return STAR.map((_, index) => `star.${index + 1}`);
}

export function bellLines(): readonly string[] {
  return BELL.map((_, index) => `bell.${index + 1}`);
}

export function closingLines(): readonly string[] {
  return CLOSING.map((_, index) => `closing.${index + 1}`);
}

export function closedLines(): readonly string[] {
  return CLOSED.map((_, index) => `closed.${index + 1}`);
}

/** "Chceš koupit maliny za tři hvězdičky?" – the id carries the item id, so it reads in the log. */
export function shopAskLine(id: string): string {
  return `shop.ask.${id}`;
}

export function shopBoughtLine(id: string): string {
  return `shop.bought.${id}`;
}

/** 1…5; anything else has no clip and `hasLine()` says so – the game then simply stays silent. */
export function shopShortLine(missing: number): string {
  return `shop.short.${missing}`;
}

export function shopHelloLines(): readonly string[] {
  return SHOP_HELLO.map((_, index) => `shop.hello.${index + 1}`);
}

const lines: Line[] = [];
const ids = new Set<string>();

/**
 * Duplicates are skipped, not reported: the same letter+word pair legitimately arrives from both
 * LETTER_WORDS and ROLE_WORDS (M jako maminka). Everything else is unique by construction and the
 * test guards it.
 */
function add(id: string, text: string): void {
  if (ids.has(id)) return;
  ids.add(id);
  lines.push({ id, text });
}

// One set for everything that is counted, because everything that is counted is fruit – on the
// cake today, on the pancakes and the milkshake later.
for (const fruit of FRUITS) {
  for (const amount of DIGITS) {
    add(orderCountLine(amount, fruit), `Prosím ${countedFruit(amount, fruit)}.`);
    add(orderNextCountLine(amount, fruit), `A ještě ${countedFruit(amount, fruit)}.`);
    add(countEnoughLine(amount, fruit), `Už máme ${countedFruit(amount, fruit)}, to stačí!`);
  }
}

// The sentence that ASKS for a letter or a digit names what carries it, and that is different on
// every product ("perníček" × "oplatku"). Everything else about an element – how it is counted out
// loud, what to say to a wrong one, where to look – is about the letter itself and stays one set.
for (const product of PRODUCTS) {
  const texts = PRODUCT_TEXTS[product.id];
  for (const digit of DIGITS) {
    add(orderDigitLine(digit, product.id), `Prosím ${texts.digit} s číslem ${CARDINALS[digit]}.`);
    add(
      orderNextDigitLine(digit, product.id),
      `A ještě ${texts.digit} s číslem ${CARDINALS[digit]}.`,
    );
  }
  for (const letter of BASE_LETTERS) {
    const spelled = SPELLED[letter];
    add(orderLetterLine(letter, product.id), `Prosím ${texts.letter} s písmenkem ${spelled}.`);
    add(orderNextLetterLine(letter, product.id), `A ještě ${texts.letter} s písmenkem ${spelled}.`);
  }
}

for (const digit of DIGITS) {
  const target = String(digit);
  add(countAloudLine(digit), `${capitalize(CARDINALS[digit])}.`);
  add(wrongLine(target), `To je ${DIGIT_NAMES[digit]}.`);
  add(seekLine(target), `Hledáme ${DIGIT_NAMES_ACC[digit]}.`);
  add(hintLine(target), `${capitalize(DIGIT_NAMES[digit])} je tady!`);
}

for (const letter of BASE_LETTERS) {
  const spelled = SPELLED[letter];
  add(wrongLine(letter), `To je ${spelled}.`);
  add(seekLine(letter), `Hledáme ${spelled}.`);
  add(hintLine(letter), `${capitalize(spelled)} je tady!`);
  add(
    letterWordLine(letter, LETTER_WORDS[letter]),
    `${capitalize(SPELLED_IN_WORD_LINE[letter] ?? spelled)} jako ${LETTER_WORDS[letter]}.`,
  );
}

// Family words on top of the defaults: brácha, ségra, babička, děda (maminka and táta are already
// in LETTER_WORDS). Which of them the child hears is decided by the settings at runtime.
for (const entry of ROLE_WORDS) {
  add(
    letterWordLine(entry.letter, entry.word),
    `${capitalize(SPELLED[entry.letter])} jako ${entry.word}.`,
  );
}

for (const gender of ['neutral', 'female', 'male'] as const) {
  const texts = PRAISE[gender];
  for (const [index, text] of texts.entries()) add(`praise.${gender}.${index + 1}`, text);
}

for (const [index, entry] of FINISH.entries()) add(`finish.${index + 1}`, entry.text);
for (const [index, text] of STAR.entries()) add(`star.${index + 1}`, text);
for (const [index, text] of BELL.entries()) add(`bell.${index + 1}`, text);
for (const [index, text] of CLOSING.entries()) add(`closing.${index + 1}`, text);
for (const [index, text] of CLOSED.entries()) add(`closed.${index + 1}`, text);
// Driven by the catalogue, so the shelf and the narrator can never hold different things.
for (const item of SHOP_ITEMS) {
  const texts = SHOP_TEXTS[item.id];
  add(shopAskLine(item.id), texts.ask);
  add(shopBoughtLine(item.id), texts.bought);
}
for (const [index, text] of SHOP_SHORT.entries()) add(shopShortLine(index + 1), text);
for (const [index, text] of SHOP_HELLO.entries()) add(`shop.hello.${index + 1}`, text);
add(OPEN_LINE, OPEN_TEXT);
add(TURN_LINE, TURN_TEXT);

export const LINES: readonly Line[] = lines;

/** Does the clip exist? Every helper returns an id even for input out of range, this decides. */
export function hasLine(id: string): boolean {
  return ids.has(id);
}
