/**
 * The manifest of every sound effect in the game (docs/navrh-hry.md ch. 8). One id = one file
 * `public/audio/sfx/<id>.mp3`, generated by `scripts/generate-sfx.mjs` from the prompt next to it
 * and committed, so the game never touches the network (CLAUDE.md rules 5 and 9).
 *
 * The prompts are ENGLISH on purpose. They are not game content – the child never hears a word of
 * them – but a technical input to a model trained on English; the language policy covers the UI,
 * not the parameters of a generator. What the child hears has no words at all: the customers only
 * make sounds, the narrator is the only one who speaks (rozhodnutí autora, srpen 2026).
 *
 * CAREFUL: read by plain Node too (the generator, type stripping), so this file stays import-free
 * – the same rule as lines.cs.ts and voices.ts.
 */
export interface SoundEffect {
  /** Id and file name at once: `^[a-z0-9]+([.-][a-z0-9]+)*$` → public/audio/sfx/<id>.mp3 */
  readonly id: string;
  /** English prompt for the ElevenLabs Sound Effects endpoint. */
  readonly prompt: string;
  /** 0.5–30 s. A short effect is cheaper and has a sharper attack – most of ours are under 1.5. */
  readonly durationSeconds: number;
  /** 0–1, the API default is 0.3. Higher sticks to the prompt and improvises less. */
  readonly promptInfluence?: number;
}

/**
 * The counting ladder is ONE clip. Text-to-sound-effects cannot be told a pitch, so five separate
 * prompts would give five unrelated dings; `pling` is played back at five playback rates instead
 * (see PLING_SEMITONES). One file, one sound, a clean rising scale.
 */
export const SFX: readonly SoundEffect[] = [
  {
    id: 'whoosh',
    prompt: 'soft quick whoosh of a small object flying through the air, cartoon, clean, no music',
    durationSeconds: 0.6,
  },
  {
    id: 'pling',
    prompt: 'short bright glockenspiel ding, single clean note, no reverb tail',
    durationSeconds: 0.8,
  },
  {
    id: 'done',
    prompt: 'warm friendly two-note kitchen oven timer ping, cheerful, clean',
    durationSeconds: 1.2,
  },
  {
    id: 'nope',
    prompt: 'soft low wooden bump, gentle and encouraging, cartoon, not harsh',
    durationSeconds: 0.6,
  },
  {
    id: 'bell',
    prompt: 'small brass shop counter desk bell rung once, bright ding',
    durationSeconds: 1.5,
  },
  {
    id: 'sparkle',
    prompt: 'short magical sparkle twinkle, bright, cartoon reward',
    durationSeconds: 1.0,
  },
  {
    id: 'steps',
    prompt: 'soft padding footsteps of a small animal on a wooden floor, four light steps',
    durationSeconds: 1.5,
  },
  {
    id: 'munch',
    prompt: 'cute cartoon character taking a bite and chewing happily, soft',
    durationSeconds: 1.5,
  },
  {
    id: 'customer.bear.hello',
    prompt: 'friendly low cartoon bear grunt, warm and short, no words',
    durationSeconds: 1.0,
  },
  {
    id: 'customer.bear.yum',
    prompt: 'happy cartoon bear contented low hum, no words',
    durationSeconds: 1.0,
  },
  {
    id: 'customer.rabbit.hello',
    prompt: 'cute high cartoon rabbit squeak, friendly and short, no words',
    durationSeconds: 1.0,
  },
  {
    id: 'customer.rabbit.yum',
    prompt: 'happy cartoon rabbit nibble squeak, cheerful, no words',
    durationSeconds: 1.0,
  },
  {
    id: 'customer.cat.hello',
    prompt: 'soft friendly cartoon cat meow, short, no words',
    durationSeconds: 1.0,
  },
  {
    id: 'customer.cat.yum',
    prompt: 'contented cartoon cat purr with a small mrrp, short',
    durationSeconds: 1.0,
  },
];

const IDS: ReadonlySet<string> = new Set(SFX.map((effect) => effect.id));

export function hasSfx(id: string): boolean {
  return IDS.has(id);
}

/** Where the clip lives, relative to the site root – the game never builds this path by hand. */
export function sfxPath(id: string): string {
  return `audio/sfx/${id}.mp3`;
}

/** The sound a customer makes when it walks in. */
export function customerHelloSfx(id: string): string {
  return `customer.${id}.hello`;
}

/** The sound a customer makes once it has eaten. */
export function customerYumSfx(id: string): string {
  return `customer.${id}.yum`;
}

/**
 * The rungs of the counting ladder in semitones above `pling` (C5 D5 E5 G5 A5) – the same scale the
 * oscillators used to synthesise before the clips existed. A step past the end wraps around, so an
 * order longer than five pieces (STEP-11) keeps climbing instead of running out.
 */
export const PLING_SEMITONES: readonly number[] = [0, 2, 4, 7, 9];

export function plingRate(step: number): number {
  const count = PLING_SEMITONES.length;
  const index = Number.isFinite(step) ? ((Math.trunc(step) % count) + count) % count : 0;
  return 2 ** ((PLING_SEMITONES[index] ?? 0) / 12);
}
