/**
 * The narrators the game can speak with (docs/navrh-hry.md ch. 8). One row = one full set of clips
 * in `public/audio/voice/<slug>/`, generated by `scripts/generate-voice.mjs`. Adding a voice means
 * adding a row and running the generator; it fills in only the new folder.
 *
 * `label` is Czech because it is game content – it is what the child is offered once the voice
 * picker exists. Everything else, the folder name included, is English (CLAUDE.md › Language).
 *
 * CAREFUL: read by plain Node too, so this file must stay import-free (see lines.cs.ts).
 */
export interface VoiceOption {
  /** Folder name under public/audio/voice/ and the id stored in the save: `^[a-z][a-z0-9-]*$`. */
  readonly slug: string;
  /** Czech name for the child, e.g. on the portrait in the picker. */
  readonly label: string;
  /** The voice at ElevenLabs. Not a secret – using it needs the author's own paid key. */
  readonly elevenLabsId: string;
}

/** The first one is the default until the child picks (návrh kap. 8). */
export const VOICES: readonly VoiceOption[] = [
  { slug: 'cook', label: 'Kuchařka', elevenLabsId: 'bF7C2fCv7Zf30iT84wZ1' },
];

export const DEFAULT_VOICE: string = VOICES[0]?.slug ?? 'cook';

export function voiceBySlug(slug: string): VoiceOption | null {
  return VOICES.find((voice) => voice.slug === slug) ?? null;
}

/** Where the clip lives, relative to the site root – the game never builds this path by hand. */
export function clipPath(slug: string, lineId: string): string {
  return `audio/voice/${slug}/${lineId}.mp3`;
}
